idf_component_register(
    SRCS 
        "main.c" 
        "gui/lv_port_disp.c"
        "gui/lv_port_indev.c"
        "gui/ui_sensor.c"
        "gui/ui_accel.c"
        "gui/ui_gyro.c"
        "gui/ui_wifi.c"
        "gui/ui_saved_wifi.c"
        "gui/ui_nearby_wifi.c"
        "gui/ui_mqtt.c"
        "gui/ui_mqtt_interval.c"
        "gui/ui_mqtt_history.c"
        "gui/ui_mqtt_config.c"
        "gui/ui_mqtt_pub.c"
        "gui/ui_mqtt_sub.c"
        "gui/ui_led.c"
        "gui/ui_led_preset.c"
        "gui/ui_led_custom.c"
        "gui/ui_home.c"
        "gui/ui_sd.c"
        "gui/ui_files.c"
        "gui/ui_gallery.c"
        "gui/ui_sysinfo.c"
        "gui/ui_pc_perf.c"
        "gui/ui_pc_perf_cfg.c"
        "drv/ft6336.c"
        "drv/i2c_bus.c"
        "drv/key.c"
        "drv/lcd_driver.c"
        "drv/power.c"
        "drv/rgb_led.c"
        "drv/sd_card.c"
        "drv/shtc3.c"
        "drv/jy901s.c"
        "app/wifi_manager.c"
        "app/mqtt_manager.c"
        "app/time_manager.c"
        "app/ble_perf.c"
        "app/pc_perf_mqtt.c"
        "app/pc_perf_src.c"
        "app/upload_server.c"
        "app/sd_file.c"
    INCLUDE_DIRS 
        "."
        "gui"
        "app"
        "drv"
                    
    REQUIRES 
        esp_lcd 
        esp_driver_ledc 
        esp_driver_uart
        driver 
        fatfs 
        sdmmc
        esp_http_server
        led_strip
        esp_timer
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        mqtt
        lwip
        esp_partition
        bootloader_support
        esp_psram
        bt
)
